version: '3.7'

services:
    app:
        volumes:
              - static:/static
        env_file: 
              - .env
        build:
              context: .
        ports: 
              - "8000:8000"
    nginx_app:
        build: ./nginx
        volumes: 
            - static:/static
        ports:
            - "8007:80"
        depends_on: 
            - app
volumes: 
    static:
    